Feature branch. Requesting for review to merge to Master.
Daniduran-dev/newsweek pull request #5
Opened 2020-04-28 11:29 UTC by Daniduran-dev

# Newsweek clone using Bootstrap 4
- This project has been done using bootstrap properties as much as I could.
- I have been using CSS as less as I could.
Please Let me know if there's any changes needed to be approved.

2020-04-28 11:58 UTC, rOluochKe requested changes
Hello @Daniduran-dev 
### You have done a good so far :clap: However, there are changes you need to make
- Solve the conflict with the branch feature
- Your application has no images, add them
![no images](https://user-images.githubusercontent.com/8114528/80484351-43779e80-8960-11ea-9eb3-6c5823dcc9aa.PNG)
- Avoid the use of the word important in your css file
![important](https://user-images.githubusercontent.com/8114528/80484480-715ce300-8960-11ea-9c05-0aac9e8dea27.PNG)
### Make all these changes and resubmit for another code review. Good luck.
- Happy coding!

By Raymond
Slack: @iamraymond

2020-04-28 12:18 UTC, Daniduran-dev commented
Hello,
- I've just fixed the problem with the images.
- I can't identify that conflict that you mention, please be more specific.
- I don't like to use !important either but this is bootstrap, in this case there's no other solution if I don't put it bootstrap will override it and the result will be ugly.

2020-04-28 12:22 UTC, rOluochKe commented
> Hello,
> 
> * I've just fixed the problem with the images.
> * I can't identify that conflict that you mention, please be more specific.
> * I don't like to use !important either but this is bootstrap, in this case there's no other solution if I don't put it bootstrap will override it and the result will be ugly.

Ok, that is great. I also forgot, add a readme file in the project and resubmit your project for review.

2020-04-28 13:01 UTC, mikenath223 commented
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

2020-04-28 13:20 UTC, mikenath223 requested changes
### Hi @Daniduran-dev  👋

Your project looks awesome🚀

However, let's make it even more awesome:

- [x] Required - As stated in the previous review we generally want to avoid the use of the `!important` tag. Generally the use of the `!important` tag is considered a CSS bad practice please refer to this ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
![ice_screenshot_20200428-141540](https://user-images.githubusercontent.com/33323077/80491806-1a084400-895b-11ea-8f76-9cee5f90426c.png)

**Kindly fix this👇**
![ice_screenshot_20200428-140917](https://user-images.githubusercontent.com/33323077/80491871-2ee4d780-895b-11ea-9d01-c28c79f6db5a.png)

- [x] Also please make the top navbar fixed at the top as can be seen in the original webpage.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-04-28 14:20 UTC, Daniduran-dev commented
Hello,

- Navbar is sticky now. (I haven't seen it before in the projects of other students this is why I didn't do it in the beginning. It would be amazing if you guys can define what we should do and have a unified criterion to decide what projects should pass and what are the requirements, and let us know in advance, of course.)

- I have eliminated as many !important attributes as I could. The other ones are absolutely necessary for the optimal visualization of the website. I've been trying to use id instead of classes but it doesn't work. I've been looking for solutions on the internet but everybody recommends to use !important as the only solution to override a bootstrap class. I've spent a whole day before trying to find a workaround to do this but I couldn't. As you see I've found lots of workarounds to do things with bootstrap that most of the people have given up and have done it with CSS, but this one is impossible for me. I haven't found anybody who can help me with this. If you know how to do it I would love to hear your solution. Thanks in advance.

P.D. I've tried to reach you in Slack but apparently the user @michgolden doesn't exist.

2020-04-28 15:38 UTC, Daniduran-dev commented
Hello? Anybody there?

2020-04-28 16:37 UTC, mikenath223 commented
Hi Daniduran.
You can try searching out my name on slack (michgolden).

However if you have submitted a request for re-review your project will be reviewed. 

Kindly exercise patience.

2020-04-28 16:51 UTC, Daniduran-dev commented
Yeah I don't really know how these things of the review work. Let's see what happens.

2020-04-28 18:09 UTC, mikenath223 requested changes
Hi again @Daniduran-dev 

You've done quite well fixing some issues raised in the previous review.

However, the `important` tag still exists on your CSS codebase. Kindly remove all `important` tags in your CSS.

### You've really done well on this project.🚀

You are really close to a thumbs up. We've got you💪


Kindly fix these issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-04-28 18:24 UTC, Daniduran-dev commented
Thank you for attending this. Please... Read the comments I made to your partner. I cannot take the important tag. I don't know how to do it. People in stack overflow are telling me the only solution to override a css class is using the important. If I take out the important maybe I pass this project but the result will be awful... Impossible to show that in a portfolio. And let me ask you the same question I asked to your partner and is still unanswered. If you know how to do this with bootstrap without using the important tag then please I would love to see your solution.

2020-04-28 18:58 UTC, mikenath223 requested changes
### Hi @Daniduran-dev 

You can override bootstrap classes by chaining multiple selectors. Try chaining multiple CSS selectors to an element, and see the result. You can search further on this.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-04-28 19:17 UTC, Daniduran-dev commented
hi, I contacted you in slack... trying to make your solution work... no success yet.. but I'm going to bed.. its 2.16 am here

2020-04-29 09:26 UTC, Daniduran-dev commented
**PLEASE READ THIS** To The future reviewer

- I have been working on this project for a long time and I have found lots of workarounds but I'm totally stuck on one: I cant override a bootstrap class without using !important.
- I have been looking for a solution and I have even posted in StackOverflow my problem. The conclusions are always the same: I need to use important to override bootstrap.
- Apparently there's an old technique that works. But I still haven't found anybody that can do it. Sound like an urban legend to me: Apparently if you chain multiple classes or id's you can override bootstrap.
![image](https://user-images.githubusercontent.com/57133486/80579501-552a7600-8a34-11ea-98f3-042c633d1306.png)
- As you can see... I have been trying this technique using classes and id's; giving an id to each parent in HTML until arriving at the body. The result is always the same: **It doesn't work**
- So, please, if you have a technique to override a bootstrap class please share it with me. But don't limit your review to indicate that I must remove the important.
- If there's no solution, and considering that I have been a whole month working to clone with bootstrap a website that was not made with it, I, please, ask you consider accepting the use of important in this particular situation.

Thank you,
Daniel

2020-04-29 10:18 UTC, lekegitrepo commented
#### Hi @Daniduran-dev :+1: 
#### Good job. This project is approved. However, I'll suggest that you should take extra care on the application of the bootstrap on the page so that you can avoid this kind of problem next time. Because it can be tricky sometimes.

### Reviewed by Temitayo Adeleke.

- Github: [@lekegitrepo](https://github.com/lekegitrepo)
- Twitter: [@leketemi](https://twitter.com/leketemi)
- Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

2020-04-29 10:19 UTC, lekegitrepo approved these changes
#### Status: Approved.

2020-04-29 10:26 UTC, merged